#!/bin/bash

# Update the package list
sudo apt update

# Install the specified Python packages
sudo apt install -y \
  python3-pip \
  python3-dotenv \
  python3-pymongo \
  python3-dateutil \
  python3-dnspython

echo "Installation complete!"
